import './styles.css';
import {api,escape,icon,link,origin,errorBlock} from './ui';
import {setSession,subscribe} from './session';
import type {Data,Mount} from './types';
const routes:Record<string,{title:string;short:string;description:string;load:()=>Promise<{mount:Mount}>}>={
 inicio:{title:'O Início',short:'O Início',description:'Entenda o sistema e percorra a demonstração de ponta a ponta.',load:()=>import('./views/start')},
 diagnosis:{title:'Operational Diagnosis',short:'Diagnóstico',description:'Entenda a demanda, a satisfação e os limites da sua evidência.',load:()=>import('./views/diagnosis')},
 automation:{title:'AI Automation Strategy',short:'Estratégia de IA',description:'Transforme evidências em automação responsável e hipóteses mensuráveis.',load:()=>import('./views/strategy')},
 'ticket-lab':{title:'AI Ticket Lab',short:'Ticket Lab',description:'Uma nova solicitação. O mesmo modelo, as mesmas evidências.',load:()=>import('./views/lab')},
 copilot:{title:'AI Copilot',short:'Copilot',description:'Encontre referências históricas e revise cada sugestão antes de agir.',load:()=>import('./views/copilot')},
 graph:{title:'Support Intelligence Graph',short:'Rede semântica',description:'Explore famílias de problemas, vizinhanças e decisões da IA.',load:()=>import('./views/graph')},
 'command-center':{title:'Support Command Center',short:'Command Center',description:'Operação, automação e modelo em uma única visão da demonstração.',load:()=>import('./views/command')}
};
let catalog:Data={datasets:[],spaces:[],model:{}}, cleanup:(()=>void)|undefined,controller=new AbortController(),viewToken=0;
const app=document.querySelector<HTMLElement>('#app')!;
app.innerHTML=`<a class="skip-link" href="#main-content">Pular para conteúdo</a><aside class="sidebar"><a class="brand" href="#/inicio" aria-label="Support Intelligence - O Início"><img src="/assets/logo-g4-branca.svg" alt="G4" width="101" height="40"><span>Support<br><b>Intelligence</b></span></a><button class="mobile-menu button secondary" aria-expanded="false" aria-controls="main-nav">Abrir navegação</button><nav id="main-nav" aria-label="Lentes do sistema">${Object.entries(routes).map(([id,r])=>`<a data-route="${id}" href="#/${id}">${icon(id)}<span>${r.short}</span></a>`).join('')}</nav><div class="sidebar-footer"><span class="status-dot"></span><span>Um sistema.<br>Seis perspectivas.</span><small>Challenge 002 · G4</small></div></aside><div class="workspace"><header class="topbar"><span class="workspace-label">Inteligência de Suporte</span><div class="context-controls"><label for="global-dataset">Corpus</label><select id="global-dataset"><option value="ds1">Suporte ao cliente</option><option value="ds2">Suporte de TI</option></select><span id="global-source" class="badge">Histórico</span><a id="session-pill" class="session-pill" href="#/command-center">Sem sessão ativa</a></div></header><main id="main-content" tabindex="-1"><div class="page-heading"><div><h1 id="page-title">O Início</h1><p id="page-description"></p></div><div id="page-context"></div></div><div id="route-view" aria-busy="true"></div></main><footer class="app-footer"><span>Dados, decisões e evidências conectados.</span><span>Ambiente de demonstração · dados originais preservados</span></footer></div><div id="announcement" class="sr-only" role="status" aria-live="polite"></div>`;
const menu=app.querySelector<HTMLButtonElement>('.mobile-menu')!;menu.onclick=()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'Fechar navegação':'Abrir navegação';app.querySelector('.sidebar')!.classList.toggle('open',open);};
function current(){const [path,qs='']=location.hash.slice(2).split('?');return{route:routes[path]?path:'diagnosis',params:new URLSearchParams(qs)};}
 app.querySelector<HTMLSelectElement>('#global-dataset')!.onchange=e=>{const {route,params}=current();for(const key of ['space_id','ticket_id','cluster_id','channel','priority','category','status','product','csat_presence','csat_score','offset','session_id','alert_id'])params.delete(key);location.hash=link(route,params,{dataset_id:(e.target as HTMLSelectElement).value,source:'historical'});announce('Corpus alterado. Filtros incompatíveis e seleção anterior foram removidos.');};
export function announce(text:string){document.querySelector('#announcement')!.textContent=text;}
subscribe((snapshot,_events,error)=>{const pill=document.querySelector<HTMLAnchorElement>('#session-pill')!;if(snapshot){pill.textContent=error?'Sessão · reconectando':`Replay · ${{STOPPED:'parado',PLAYING:'em execução',PAUSED:'pausado',COMPLETED:'concluído'}[snapshot.state as string]||snapshot.state}`;pill.classList.toggle('playing',snapshot.state==='PLAYING'&&!error);const{params}=current();pill.href=link('command-center',params,{session_id:snapshot.session_id});}else pill.textContent='Sem sessão ativa';});
async function render(){const token=++viewToken;cleanup?.();cleanup=undefined;controller.abort();controller=new AbortController();const{route,params}=current();const dataset=params.get('dataset_id')||(route==='ticket-lab'||route==='graph'||route==='command-center'?'ds2':'ds1');params.set('dataset_id',dataset);const meta=routes[route];document.title=`${meta.short} · Support Intelligence`;app.querySelector('#page-title')!.textContent=meta.title;app.querySelector('#page-description')!.textContent=meta.description;app.querySelector<HTMLSelectElement>('#global-dataset')!.value=dataset;app.querySelector('#global-source')!.textContent=origin(params.get('source')||'historical');app.querySelector('#page-context')!.innerHTML=`<span class="context-note">${dataset==='ds1'?'Customer Support':'IT Service Tickets'}</span>`;app.querySelectorAll<HTMLAnchorElement>('[data-route]').forEach(a=>{a.href=link(a.dataset.route!,params);if(a.dataset.route===route)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});app.querySelectorAll<HTMLDialogElement>('dialog[open]').forEach(d=>d.close());app.querySelector('.sidebar')!.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='Abrir navegação';const root=app.querySelector<HTMLElement>('#route-view')!;root.innerHTML='<div class="loading"><span class="loader" aria-hidden="true"></span><p>Consultando dados e evidências…</p></div>';root.setAttribute('aria-busy','true');void setSession(params.get('session_id')||'');try{if(!catalog.datasets.length)catalog=await api('/catalog');if(token!==viewToken)return;const module=await meta.load();if(token!==viewToken)return;const result=await module.mount(root,{route,params,catalog,signal:controller.signal});if(token!==viewToken){result?.();return;}cleanup=result||undefined;root.setAttribute('aria-busy','false');announce(`${meta.title} carregado.`);}catch(e){if(token!==viewToken||controller.signal.aborted)return;root.setAttribute('aria-busy','false');root.innerHTML=errorBlock(e);root.querySelector('[data-retry]')?.addEventListener('click',()=>{catalog={datasets:[],spaces:[]};void render();});}}
window.addEventListener('hashchange',()=>void render());app.addEventListener('click',e=>{if((e.target as HTMLElement).closest('[data-retry]'))void render();});void render();
