import type {Mount,Data} from '../types';
import {api,post,escape,number,link,query,panel,notice,badge,empty,table,bindTicketDetails} from '../ui';
const drafts=new Map<string,string>();
export const mount:Mount=async(root,c)=>{
 const id=c.params.get('ticket_id');
 if(!id){const list=await api(`/tickets?${query(c,{limit:12})}`,{signal:c.signal});root.innerHTML=notice('Comece por um ticket','Selecione uma solicitação histórica ou abra o Copilot pelo Ticket Lab. A recuperação usa apenas resoluções do mesmo corpus.','neutral')+panel('Selecione uma solicitação',table(['Ticket','Contexto','Resolução histórica','Ação'],(list.items||[]).map((t:Data)=>[escape(t.subject||t.category||t.ticket_id),`<span class="ticket-snippet">${escape((t.text||'').slice(0,200))}</span>`,t.resolution?'Registrada · requer revisão':'Ausente',`<a class="button small secondary" href="${escape(link('copilot',c.params,{ticket_id:t.ticket_id,dataset_id:t.dataset_id}))}">Abrir ticket</a>`])));return;}
 const ticket=await api(`/tickets/${encodeURIComponent(id)}`,{signal:c.signal});
 root.innerHTML=`<div class="grid-even"><section class="panel"><div class="panel-heading"><h2>Ticket atual</h2>${badge(ticket.dataset_id==='ds1'?'Suporte ao cliente':'Suporte de TI')}</div><p class="ticket-text">${escape(ticket.text)}</p><small class="cell-sub">${escape(id)}</small><div class="actions section-gap"><button class="button" id="retrieve">Recuperar evidências</button><a class="button secondary" href="${escape(link('graph',c.params))}">Ver na rede</a></div><p id="copilot-error" class="form-error" role="alert"></p><hr class="subtle-divider"><p class="small muted">${ticket.dataset_id==='ds1'?'As resoluções deste corpus são genéricas e contêm templates. Encontrar um registro não comprova que a ação resolve o caso atual.':'Este corpus não possui resoluções históricas. A busca não associa artificialmente os tickets de TI ao corpus de clientes.'}</p></section><section id="suggestion" class="panel"><div class="result-empty">${empty('Assistência com rastreabilidade','Primeiro, o sistema consulta fontes históricas. Se não houver evidência suficiente, ele informa esse limite.')}</div></section></div><section id="sources" class="section-gap"></section>`;
 const retrieve=root.querySelector<HTMLButtonElement>('#retrieve')!;let requestId=crypto.randomUUID();
 retrieve.onclick=async()=>{retrieve.disabled=true;retrieve.textContent='Recuperando…';root.querySelector('#copilot-error')!.textContent='';try{const s=await post('/copilot/suggestions',{ticket_id:id,session_id:c.params.get('session_id')||undefined,request_id:requestId});if(c.signal.aborted)return;renderSuggestion(s);requestId=crypto.randomUUID();}catch(e){root.querySelector('#copilot-error')!.textContent=(e as Error).message;}finally{retrieve.disabled=false;retrieve.textContent='Recuperar novamente';}};
 function renderSuggestion(s:Data){const enough=s.status==='ready';root.querySelector('#suggestion')!.innerHTML=`<div class="panel-heading"><h2>${enough?'Referência para revisão':'Evidência insuficiente'}</h2>${badge(s.mode==='extractive'?'Recuperação extrativa':s.mode||'Sem geração')}</div>${enough?`<p class="suggestion-text">${escape(s.text)}</p>`:notice('Não é possível sustentar uma solução',s.text||'As fontes recuperadas não oferecem instruções suficientes para este caso. Encaminhe para investigação humana.')}<p class="small muted">Revisão humana obrigatória. Nenhuma resposta será enviada ao cliente.</p>${s.limitations?.length?`<ul class="quality-list">${s.limitations.map((l:string)=>`<li>${escape(l)}</li>`).join('')}</ul>`:''}${s.suggestion_id?`<div class="feedback-row"><h3>Esta referência ajudou o atendimento?</h3><div class="actions"><button class="button small" data-feedback="accept">Aceitar referência</button><button class="button small secondary" id="edit-suggestion">Editar</button><button class="button small secondary" data-feedback="reject">Rejeitar</button></div><div id="edit-area" hidden class="section-gap"><div class="field"><label for="edited-response">Sua revisão</label><textarea id="edited-response" maxlength="20000">${escape(drafts.get(s.suggestion_id)||s.text||'')}</textarea></div><button class="button small section-gap" data-feedback="edit">Salvar revisão</button></div><p id="feedback-status" class="feedback-status section-gap" role="status"></p></div>`:''}`;
 root.querySelector('#sources')!.innerHTML=panel('Fontes recuperadas e contexto utilizado',s.sources?.length?s.sources.map((t:Data,i:number)=>`<article class="source-row"><div class="actions spread"><button class="text-button" data-ticket="${escape(t.ticket_id)}">Fonte ${i+1} · ${escape(t.ticket_id)}</button>${badge(`Similaridade ${number(t.similarity,4)}`)}</div><p>${escape(t.text)}</p><details open><summary>Resolução histórica utilizada</summary><p>${escape(t.resolution||'Este registro não contém resolução.')}</p></details></article>`).join(''):empty('Nenhuma resolução recuperada','Não há fonte suficiente para propor uma ação fundamentada.'));
 bindTicketDetails(root,c);root.querySelector<HTMLButtonElement>('#edit-suggestion')?.addEventListener('click',()=>{root.querySelector<HTMLElement>('#edit-area')!.hidden=false;root.querySelector<HTMLTextAreaElement>('#edited-response')!.focus();});const edit=root.querySelector<HTMLTextAreaElement>('#edited-response');if(edit)edit.oninput=()=>drafts.set(s.suggestion_id,edit.value);
 const pending=new Map<string,string>();root.querySelectorAll<HTMLButtonElement>('[data-feedback]').forEach(b=>b.onclick=async()=>{const decision=b.dataset.feedback!,text=decision==='edit'?edit?.value.trim():undefined;if(decision==='edit'&&!text){root.querySelector('#feedback-status')!.textContent='Escreva sua revisão antes de salvar.';return;}const key=decision+':'+(text||'');if(!pending.has(key))pending.set(key,crypto.randomUUID());const buttons=root.querySelectorAll<HTMLButtonElement>('[data-feedback]');buttons.forEach(x=>x.disabled=true);try{await post('/feedback',{suggestion_id:s.suggestion_id,decision,text,request_id:pending.get(key)});root.querySelector('#feedback-status')!.textContent='Feedback registrado nesta versão. Nenhuma mensagem foi enviada.';}catch(e){root.querySelector('#feedback-status')!.textContent='Não foi possível salvar: '+(e as Error).message;}finally{buttons.forEach(x=>x.disabled=false);}});
 }
};
