import type {Mount,Data} from '../types';
import {escape,number,link,badge} from '../ui';

export const mount:Mount=async(root,c)=>{
 const ds1=c.catalog.datasets?.find((d:Data)=>d.dataset_id==='ds1'),ds2=c.catalog.datasets?.find((d:Data)=>d.dataset_id==='ds2');
 const lens=[
  ['diagnosis','1. Diagnóstico','Mostra onde a demanda se concentra e o que o Dataset 1 realmente permite medir. Use filtros de canal, prioridade, tipo, status e produto; abra os tickets que sustentam cada recorte.','Comece aqui para explicar o problema ao gestor.','ds1'],
  ['automation','2. Estratégia de IA','Converte evidências em oportunidades de automação, com limites humanos e uma calculadora de esforço/ROI baseada nas suas premissas.','Use depois do diagnóstico para decidir o que testar.','ds1'],
  ['ticket-lab','3. Ticket Lab','Recebe um texto novo e executa o mesmo pipeline: categoria, confiança, prioridade e rota sugeridas, vizinhos e possível duplicata.','Use para provar que existe uma automação funcional.','ds2'],
  ['copilot','4. Copilot','Recupera resoluções históricas do mesmo corpus para o agente revisar. A sugestão nunca é enviada automaticamente ao cliente.','Use quando quiser mostrar rastreabilidade e revisão humana.','ds1'],
  ['graph','5. Rede semântica','Organiza grupos, tickets e vizinhanças calculadas por embeddings. Clique em um nó ou use a tabela para abrir a evidência.','Use para investigar relações, clusters e alertas.','ds2'],
  ['command-center','6. Command Center','Reproduz chegadas de tickets históricos em uma sessão controlada e acompanha decisões, alertas, latência e saúde do modelo.','Use por último para contar a operação de ponta a ponta.','ds2']
 ];
 const jump=(route:string,dataset:string)=>link(route,c.params,{dataset_id:dataset,source:'historical',session_id:null,ticket_id:null,cluster_id:null,alert_id:null,space_id:null});
 const steps=[['Escolha o corpus.','Use o seletor “Corpus” no topo. Não misture atributos: DS1 responde perguntas operacionais; DS2 responde perguntas de classificação.'],['Entenda o retrato histórico.','Na aba Diagnóstico, leia volume, status, CSAT e cruzamentos. FRT/TTR aparecem como indisponíveis porque os arquivos não trazem uma abertura válida.'],['Decida o que automatizar.','Na Estratégia de IA, compare classificação, vizinhos e referências. Leia sempre a coluna de revisão humana e simule o ROI com premissas que você consegue defender.'],['Prove com um texto novo.','No Ticket Lab, descreva um caso realista. Confira categoria, escore, limiar de revisão, rota, vizinhos e origem antes de avançar.'],['Revise uma referência.','No Copilot, abra um ticket do DS1, recupere as fontes e aceite, edite ou rejeite a referência. A tela deixa claro que nada é enviado ao cliente.'],['Investigue a rede.','No Graph, veja a projeção 2D como aproximação. Clique em grupos/tickets ou troque para Tabela; scores de similaridade ficam visíveis junto da evidência.'],['Mostre a operação.','No Command Center, crie um Live Replay, use Play/Pause/Speed e acompanhe métricas, alertas e decisões. Replay concluído não significa ticket resolvido.'],['Feche com honestidade.','Separe o que foi observado, o que é hipótese e o que ainda precisa de piloto humano, dados temporais, autenticação e monitoramento de produção.']];
 const rationale=[
  'Quando comecei, eu não queria construir seis páginas independentes. Eu queria criar um único sistema de Inteligência de Suporte, observado por seis perspectivas diferentes. Cada aba responde a uma pergunta: onde está o problema, o que pode ser automatizado, como a IA se comporta, que evidência ajuda o agente, como os tickets se relacionam e como tudo funciona durante uma operação simulada.',
  'Primeiro, eu esbocei a ideia com o Hermes, um agente de prompt. Expliquei o problema de negócio, os datasets disponíveis e o tipo de solução que eu imaginava. Pedi para ele organizar esse raciocínio e transformar minha ideia em um prompt robusto, com contexto, objetivos, restrições e entregas claras.',
  'Depois, enviei esse prompt ao Codex com instruções específicas. Pedi que ele lesse os READMEs, analisasse os dados, respeitasse o Design System da G4, criasse a arquitetura compartilhada, documentasse cada aba em uma Spec e montasse um plano de implementação com sprints e checkpoints. Eu quis começar pela fase de planejamento antes de executar qualquer código, para deixar claro o que seria construído, quais evidências seriam necessárias e quais limitações não poderiam ser escondidas.',
  'Durante a análise dos dados, eu separei os papéis dos dois datasets. O Dataset 1 possui informações operacionais, CSAT e resoluções. O Dataset 2 possui textos de tickets de TI e oito categorias. Como eles têm estruturas e finalidades diferentes, eu mantive os dois corpora separados e não criei relações artificiais entre eles.',
  'Para a aplicação, escolhi Python com FastAPI no backend porque precisava de uma API simples, tipada e capaz de carregar os artefatos de machine learning. Usei SQLite para o catálogo sanitizado, sessões, eventos e feedback, porque ele é suficiente para uma demonstração local e permite persistir o estado sem criar uma infraestrutura complexa. No frontend, usei Vite e TypeScript. O Graph usa Sigma.js e Graphology, que permitem explorar os nós, arestas e vizinhanças no navegador. O projeto usa pnpm para instalar e gerar o build do frontend.',
  'Para NLP, eu queria uma solução mensurável, rápida e reproduzível. O classificador foi treinado no Dataset 2 usando TF-IDF, que transforma palavras e combinações de palavras em características numéricas, junto com regressão logística, que aprende a associar esses padrões às oito categorias. Escolhi essa abordagem porque ela é leve, fácil de auditar e adequada para um protótipo em que eu precisava explicar como a decisão foi tomada. Separei treino, validação e teste por grupos de textos normalizados para reduzir o risco de textos duplicados aparecerem em mais de uma etapa. A avaliação em um conjunto de teste separado alcançou 86,1% de acurácia e Macro F1 de 0,860.',
  'Também calibrei a confiança usando a validação e adotei um limiar de 75% como política experimental de revisão. Esse valor não significa que a IA esteja certa em 75% de todos os casos. Ele indica uma regra de demonstração: quando a confiança é baixa, quando o contexto é sensível ou quando falta evidência, o sistema encaminha o caso para uma pessoa.',
  'Para busca semântica e para o Graph, usei o paraphrase-multilingual-MiniLM-L12-v2. Escolhi um encoder multilíngue porque a interface está em português, enquanto os datasets contêm principalmente textos em inglês. Os textos viram embeddings normalizados, que são pesquisados com similaridade de cosseno no FAISS. HDBSCAN agrupa os textos e UMAP cria uma projeção visual em duas dimensões. Essa rede mostra relações semânticas entre tickets; ela não representa os neurônios internos do classificador.',
  'Eu também decidi não depender de uma API externa de LLM para o núcleo da demonstração. Assim, o classificador, a busca, o Graph e o Copilot continuam funcionando localmente, com custo previsível e comportamento reproduzível. O Copilot recupera resoluções históricas e produz um rascunho para revisão; ele não envia mensagens automaticamente ao cliente.',
  'A decisão central foi construir assistência controlada, e não automatizar tudo. A IA pode classificar, encontrar casos semelhantes, sugerir uma rota e destacar possíveis duplicatas. O agente continua responsável por revisar situações ambíguas, baixa confiança, riscos e respostas ao cliente. Dessa forma, a tecnologia acelera o trabalho sem transformar uma hipótese em decisão definitiva.'
 ];
 root.innerHTML=`<section class="start-hero panel"><div class="start-kicker">GUIA DE OPERAÇÃO · CHALLENGE 002</div><h2>Um sistema. Seis lentes. Uma decisão revisável.</h2><p>Esta tela explica como percorrer o Support Intelligence sem conhecimento técnico. O sistema combina diagnóstico, busca semântica, classificação e simulação para ajudar o time a decidir onde a IA pode acelerar o atendimento e onde um humano precisa assumir.</p><div class="actions"><a class="button" href="${escape(jump('diagnosis','ds1'))}">Começar pelo diagnóstico</a><a class="button secondary" href="${escape(jump('ticket-lab','ds2'))}">Testar um ticket</a></div></section><section class="panel start-rationale section-gap"><div class="panel-heading"><div><h2>O que eu pensei quando desenvolvi a solução</h2><p class="muted small">Minha linha de raciocínio, da primeira hipótese à implementação.</p></div>${badge('Planejamento antes da execução','gold')}</div><div class="start-rationale-copy">${rationale.map(text=>`<p>${escape(text)}</p>`).join('')}</div></section><div class="start-status">${badge('Dados carregados')}${badge(`DS1 · ${number(ds1?.count)} registros`)}${badge(`DS2 · ${number(ds2?.count)} registros`)}</div><section class="panel start-local section-gap"><div class="panel-heading"><div><h2>Como executar em ambiente local</h2><p class="muted small">O mesmo processo serve a API e a interface para a demonstração.</p></div>${badge('Comando único','gold')}</div><p>Abra um terminal na raiz do repositório, execute os dois comandos abaixo e mantenha essa janela aberta:</p><pre class="start-command" aria-label="Comando para iniciar o Support Intelligence"><code>cd challenges/process-002-support
.venv/bin/python -m uvicorn backend.app:app --host 127.0.0.1 --port 8000</code></pre><ol class="start-local-steps"><li>Acesse <a class="text-link" href="http://127.0.0.1:8000/#/inicio">http://127.0.0.1:8000/#/inicio</a> no navegador.</li><li>Se você alterou o frontend, gere antes o build com <code>pnpm --dir frontend run build</code>.</li><li>Para encerrar o servidor, volte ao terminal e pressione <kbd>Ctrl</kbd> + <kbd>C</kbd>.</li></ol><p class="small muted">A pasta <code>.venv</code> precisa existir e conter as dependências Python do projeto. A API lê os artefatos e o banco local dessa mesma pasta do desafio.</p></section><section class="panel section-gap"><div class="panel-heading"><div><h2>O caminho recomendado</h2><p class="muted small">Siga os passos na ordem para contar uma história de negócio, evidência, automação e controle.</p></div>${badge('Roteiro de ponta a ponta','gold')}</div><ol class="start-path">${steps.map(([title,body],i)=>`<li><span class="start-step-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><div><strong>${escape(title)}</strong><span>${escape(body)}</span></div></li>`).join('')}</ol></section><section class="panel section-gap"><div class="panel-heading"><div><h2>As seis lentes em linguagem simples</h2><p class="muted small">Cada cartão abre a mesma aplicação com o contexto adequado.</p></div></div><div class="lens-grid">${lens.map(([route,title,body,use,dataset])=>`<article class="lens-card"><div class="lens-index">${escape(title.slice(0,1))}</div><div><h3>${escape(title.slice(3))}</h3><p>${escape(body)}</p><small>${escape(use)}</small><a class="text-link" href="${escape(jump(route,dataset))}">Abrir ${escape(title.slice(3))} →</a></div></article>`).join('')}</div></section><section class="panel section-gap"><div class="panel-heading"><h2>Como ler um resultado</h2>${badge('Regra de ouro')}</div><ul class="quality-list"><li><strong>Histórico:</strong> registro que veio do CSV original; descreve o passado disponível.</li><li><strong>Simulação:</strong> conteúdo histórico reordenado para demonstrar processamento; não é tráfego de produção.</li><li><strong>Entrada manual:</strong> texto digitado no Lab e persistido com sua própria identidade.</li><li><strong>Confiança:</strong> escore do classificador. Similaridade e posição no Graph são medidas diferentes.</li><li><strong>Revisão humana:</strong> política de segurança; baixa confiança, idioma fora do benchmark e risco alto pedem julgamento.</li><li><strong>Indisponível:</strong> faltou dado ou validação. O sistema não transforma ausência em zero.</li></ul></section>`;
};
