import {api} from './ui.ts';
import type {Data} from './types';
let current:Data|null=null,sessionId='',timer:ReturnType<typeof setTimeout>|undefined,generation=0,cursor=0,failures=0;
const listeners=new Set<(snapshot:Data|null,events:Data[],error?:string)=>void>();
type RequestFailure=Error&{status?:number};
export const snapshot=()=>current;
export function subscribe(fn:(s:Data|null,e:Data[],err?:string)=>void){listeners.add(fn);if(current)fn(current,[]);return()=>{listeners.delete(fn);};}
export async function setSession(id:string){if(id===sessionId)return;sessionId=id;generation++;current=null;cursor=0;failures=0;clearTimeout(timer);if(id)await poll(generation);else listeners.forEach(f=>f(null,[]));}
export function adoptSession(s:Data){generation++;clearTimeout(timer);sessionId=s.session_id;current=s;cursor=s.last_seq||0;failures=0;listeners.forEach(f=>f(s,[]));const gen=generation;timer=setTimeout(()=>poll(gen),1000);}
async function poll(gen:number){const id=sessionId;try{let events:Data[]=[],next=current,nextCursor=cursor;if(current){const response=await api(`/sessions/${encodeURIComponent(id)}/events?after_seq=${cursor}`);if(gen!==generation)return;events=response.items||[];if(events.length||response.resync_required){next=await api(`/sessions/${encodeURIComponent(id)}/snapshot`);nextCursor=next!.last_seq||response.next_seq||cursor;}}else{next=await api(`/sessions/${encodeURIComponent(id)}/snapshot`);nextCursor=next!.last_seq||0;}if(gen!==generation)return;current=next;cursor=nextCursor;failures=0;listeners.forEach(f=>f(current,events));}catch(e){if(gen!==generation)return;const error=e as RequestFailure;if(error.status===422&&error.message.includes('Cursor posterior ao log')){try{const next=await api(`/sessions/${encodeURIComponent(id)}/snapshot`);if(gen!==generation)return;current=next;cursor=next.last_seq||0;failures=0;listeners.forEach(f=>f(current,[]));}catch(resync){failures++;listeners.forEach(f=>f(current,[],resync instanceof Error?resync.message:String(resync)));}}else{failures++;listeners.forEach(f=>f(current,[],error.message));}}if(gen===generation)timer=setTimeout(()=>poll(gen),Math.min(15000,failures?1000*2**failures:current?.state==='PLAYING'?1000:4000));}
