import type { Context, Data } from './types';
const apiBase = (import.meta.env?.VITE_API_BASE_URL || '').replace(/\/$/, '');
export const escape = (value: unknown): string => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const number = (v: unknown, digits = 0) => v == null || !Number.isFinite(Number(v)) ? '—' : new Intl.NumberFormat('pt-BR',{maximumFractionDigits:digits}).format(Number(v));
export const percent = (v: unknown) => v == null ? '—' : `${number(Number(v)*100,1)}%`;
export const origin = (v: string) => ({historical:'Histórico',simulation:'Live Replay · Simulação',user_created:'Entrada manual',model_evaluation:'Avaliação do modelo'}[v] || v || 'Histórico');
export function badge(text: unknown, variant='') {return `<span class="badge ${variant}">${escape(text)}</span>`;}
export function notice(title: string, body: string, variant='') {return `<div class="notice ${variant}"><strong>${escape(title)}</strong><p>${escape(body)}</p></div>`;}
export function empty(title:string,body:string) {return `<div class="empty"><h2>${escape(title)}</h2><p>${escape(body)}</p></div>`;}
export function errorBlock(error:unknown) {return `<div class="notice danger" role="alert"><strong>Não foi possível carregar esta informação</strong><p>${escape(error instanceof Error ? error.message : error)}</p><button class="button secondary" data-retry>Tentar novamente</button></div>`;}
export async function api(path:string, options:RequestInit={}) : Promise<any> {
 const res=await fetch(`${apiBase}/api${path}`,{...options,headers:{'Content-Type':'application/json',...options.headers}});
 const body=await res.json().catch(()=>({detail:'O servidor retornou uma resposta inválida.'}));
 if(!res.ok) throw Object.assign(new Error(typeof body.detail==='string'?body.detail:body.detail?.message||body.message||`Serviço indisponível (${res.status}).`),{status:res.status});
 return body;
}
export const post = (path:string, body:Data) => api(path,{method:'POST',body:JSON.stringify(body)});
export function link(route:string,params:URLSearchParams,patch:Data={}) {const p=new URLSearchParams(params);if(patch.dataset_id&&patch.dataset_id!==params.get('dataset_id'))for(const key of ['space_id','ticket_id','cluster_id','alert_id','session_id','channel','priority','category','status','product','csat_presence','csat_score','offset'])if(!(key in patch))p.delete(key);for(const [k,v] of Object.entries(patch)){if(v==null||v==='')p.delete(k);else p.set(k,String(v));}return `#/${route}${p.size?'?'+p.toString():''}`;}
export function go(route:string,params:URLSearchParams,patch:Data={}) {location.hash=link(route,params,patch);}
export function spaceFor(c:Context) {return c.catalog.spaces?.find((s:Data)=>s.space_id===c.params.get('space_id')) || c.catalog.spaces?.find((s:Data)=>s.dataset_id===(c.params.get('dataset_id')||'ds1'));}
export function query(c:Context,extra:Data={}) {const p=new URLSearchParams(c.params);for(const k of ['ticket_id','model_version','source','space_id','session_id','alert_id']) p.delete(k);for(const[k,v] of Object.entries(extra)){if(v==null||v==='')p.delete(k);else p.set(k,String(v));}return p.toString();}
export function metric(label:string,value:string,detail:string,href?:string) {return `<${href?'a':'div'} class="metric" ${href?`href="${escape(href)}"`:''}><span>${escape(label)}</span><strong>${escape(value)}</strong><small>${escape(detail)}</small>${href?'<span class="metric-arrow" aria-hidden="true">↗</span>':''}</${href?'a':'div'}>`;}
export function panel(title:string,body:string,action='') {return `<section class="panel"><div class="panel-heading"><h2>${escape(title)}</h2>${action}</div>${body}</section>`;}
export function table(headers:string[],rows:string[][],caption='') {return `<div class="table-scroll" tabindex="0" role="region" aria-label="${escape(caption||headers.join(', '))}"><table>${caption?`<caption>${escape(caption)}</caption>`:''}<thead><tr>${headers.map(h=>`<th scope="col">${escape(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">Sem registros neste recorte.</td></tr>`}</tbody></table></div>`;}
export function bars(counts:Data, label:string,c?:Context,dimension?:string) {const entries=Object.entries(counts||{}).map(([k,v])=>[k,Number(typeof v==='object'?v.count:v)] as const).sort((a,b)=>b[1]-a[1]);const max=Math.max(1,...entries.map(x=>x[1]));return `<div class="bar-chart" role="group" aria-label="${escape(label)}">${entries.map(([k,v])=>`<${c?'a':'div'} class="bar-row" ${c?`href="${escape(link(c.route,c.params,{[dimension!]:k}))}"`:''}><span>${escape(k)}</span><div class="bar-track" aria-hidden="true"><div style="width:${v/max*100}%"></div></div><b>${number(v)}</b></${c?'a':'div'}>`).join('')}</div>`;}
export function ticketRows(items:Data[],c:Context) {return items.map(t=>[ `<button class="text-button" data-ticket="${escape(t.ticket_id)}">${escape(t.subject||t.category||t.predicted_category||'Ticket')}</button><small class="cell-sub">${escape(t.ticket_id)}</small>`,escape((t.text||'').slice(0,130)),escape(t.category||t.predicted_category||'—'),badge(origin(t.source)),`<a class="text-link" href="${escape(link('graph',c.params,{ticket_id:t.ticket_id,dataset_id:t.dataset_id||c.params.get('dataset_id'),session_id:t.session_id||c.params.get('session_id'),source:t.source,model_version:t.model_version,space_id:t.space_id||spaceFor(c)?.space_id}))}">Explorar</a>`]);}
export function bindTicketDetails(root:HTMLElement,c:Context){root.querySelectorAll<HTMLButtonElement>('[data-ticket]').forEach(b=>b.onclick=()=>showTicket(b.dataset.ticket!,c,b));}
export async function showTicket(id:string,c:Context,trigger?:HTMLElement){const dialog=document.createElement('dialog');dialog.className='ticket-dialog';dialog.innerHTML='<div class="dialog-top"><h2>Detalhe do ticket</h2><button class="icon-button" aria-label="Fechar detalhe">×</button></div><div class="dialog-content"><p>Carregando evidências…</p></div>';document.body.append(dialog);dialog.querySelector('button')!.onclick=()=>dialog.close();dialog.addEventListener('close',()=>{dialog.remove();trigger?.focus()},{once:true});dialog.showModal();try{const t=await api(`/tickets/${encodeURIComponent(id)}`);dialog.querySelector('.dialog-content')!.innerHTML=`<div class="badge-row">${badge(origin(t.source))}${badge(t.dataset_id||'')}${badge(t.category||t.predicted_category||'Sem categoria')}</div><p class="ticket-text">${escape(t.text)}</p><dl class="facts"><div><dt>Identificador</dt><dd>${escape(id)}</dd></div><div><dt>Status observado</dt><dd>${escape(t.status||'Indisponível')}</dd></div><div><dt>CSAT</dt><dd>${t.csat==null?'Indisponível':number(t.csat,1)+'/5'}</dd></div></dl>${t.resolution?panel('Resolução registrada',`<p>${escape(t.resolution)}</p><small>Referência histórica. Este texto não comprova solução para outro caso.</small>`):''}<div class="actions"><a class="button" href="${escape(link('copilot',c.params,{ticket_id:id,dataset_id:t.dataset_id,session_id:t.session_id||c.params.get('session_id'),source:t.source,model_version:t.model_version,space_id:t.space_id||spaceFor(c)?.space_id}))}">Abrir no Copilot</a><a class="button secondary" href="${escape(link('graph',c.params,{ticket_id:id,dataset_id:t.dataset_id,space_id:t.space_id||spaceFor(c)?.space_id}))}">Ver na rede</a></div>`;dialog.querySelectorAll('a').forEach(a=>a.onclick=()=>dialog.close());}catch(e){dialog.querySelector('.dialog-content')!.innerHTML=errorBlock(e);}}
export const icon = (name:string) => {const paths:Data={inicio:'M4 10.5 12 4l8 6.5M6.5 9v10h11V9M9.5 19v-5h5v5',diagnosis:'M4 20V10m8 10V4m8 16v-7',automation:'M4 7h16M4 17h16M8 4v6m8 4v6', 'ticket-lab':'M9 3h6m-5 0v6l-6 10a1 1 0 0 0 1 2h14a1 1 0 0 0 1-2L14 9V3M8 15h8',copilot:'M4 4h16v12H8l-4 4V4m4 4h8m-8 4h5',graph:'M7 7l10 1M6 9l5 9m7-8-5 8M4 4h4v4H4zM17 6h4v4h-4zM10 17h4v4h-4z','command-center':'M3 4h18v13H3zM8 21h8m-4-4v4M6 12l3-4 4 6 3-5 2 3'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.diagnosis}"/></svg>`;};
